import Foundation
func event(_ s: String, _ e: String, _ status: String, _ turn: String = "t1", agent: String = "") -> [String: Any] {
    ["session_id":s, "event":e, "status":status, "turn_id":turn, "agent_id":agent, "token":UUID().uuidString]
}
let f = FamilyStore()
f.ingest(event("test-a","UserPromptSubmit","thinking"))
f.ingest(event("test-b","UserPromptSubmit","thinking"))
f.ingest(event("test-b","PostToolUse","working"))
assert(f.nodes["test-a"]!.status == "thinking" && f.nodes["test-b"]!.status == "working")
assert(f.selectedID == "test-a")
for i in 1...3 { f.ingest(event("test-a","SubagentStart","working",agent:"child-\(i)")) }
assert(f.children("test-a").count == 3 && f.children("test-b").isEmpty)
f.ingest(event("test-a","SubagentStop","success",agent:"child-1"), now: Date().addingTimeInterval(-1))
assert(f.children("test-a").count == 3 && f.nodes["test-a"]!.active)
f.ingest(event("test-a","SubagentStop","success",agent:"child-2"), now: Date().addingTimeInterval(-4))
assert(f.children("test-a").map{$0.id} == ["child-1","child-3"])
f.ingest(event("test-a","Interrupt","interrupted"))
f.ingest(event("test-a","PostToolUse","working"));assert(f.nodes["test-a"]!.status == "interrupted")
f.ingest(event("test-a","UserPromptSubmit","thinking","t2"))
f.ingest(event("test-a","Stop","success","t1"));assert(f.nodes["test-a"]!.status == "thinking")
f.ingest(event("test-a","PreCompact","compacting","t2"))
f.ingest(event("test-a","PostToolUse","working","t2"));assert(f.nodes["test-a"]!.status == "compacting")
f.ingest(event("test-a","PostCompact","success","t2"));assert(f.nodes["test-a"]!.status == "success")
f.ingest(event("test-b","PermissionRequest","permission"));assert(f.nodes["test-a"]!.status == "success")
f.ingest(event("test-a","PreCompact","compacting","manual-compact"))
assert(f.nodes["test-a"]!.status == "compacting")
f.ingest(event("test-a","PostCompact","success","manual-compact"))
assert(f.nodes["test-a"]!.status == "success")
print("family_store_tests=passed: isolation, selection, 3 slots, celebration retention, removal, late tool, stale turn, compaction, permission ownership")
// Parent interruption pauses its children; verified resume releases the parent.
f.ingest(event("test-a","Interrupt","interrupted","manual-compact"))
assert(f.childIsPaused(f.nodes["child-3"]!))
f.ingest(event("test-a","ResumeDetected","working","resumed-turn"))
assert(f.nodes["test-a"]!.status == "working")
assert(!f.childIsPaused(f.nodes["child-3"]!))
f.ingest(event("test-a","PostToolUse","working","manual-compact"))
assert(f.nodes["test-a"]!.turn == "resumed-turn")
f.ingest(event("test-a","Stop","success","resumed-turn"))
assert(f.nodes["test-a"]!.unread && f.roots.contains { $0.id == "test-a" })
f.markResultOpened("test-a");assert(!f.nodes["test-a"]!.unread)
let readFixture: [String:Any] = ["electron-thread-read-state-v1":["version":1,"unreadByIdentity":["account":["local:host":["test-a"]]]]]
assert(codexUnreadIDs(from:readFixture) == ["test-a"])
assert(codexUnreadIDs(from:[:]) == nil)
let file = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString+".jsonl")
let stamp = ISO8601DateFormatter().string(from:Date())
try (String(repeating:"中文测试",count:40000)+"\n"+"{\"type\":\"event_msg\",\"timestamp\":\"\(stamp)\",\"payload\":{\"type\":\"task_started\",\"turn_id\":\"resume-proof\"}}\n").write(to:file,atomically:true,encoding:.utf8)
assert(latestLifecycle(at:file.path)?.turn == "resume-proof")
try FileManager.default.removeItem(at:file)
print("pause, verified resume, stale events, unread lifecycle and partial UTF-8 log tests passed")
let selection = FamilyStore()
selection.selectedID = "finished-old-thread"
selection.ingest(event("first","UserPromptSubmit","thinking"));selection.reconcileSelection()
assert(selection.selectedID == "first")
selection.ingest(event("second","UserPromptSubmit","thinking"));selection.reconcileSelection()
assert(selection.selectedID == "second")
selection.select("first")
selection.ingest(event("second","PostToolUse","working"));selection.reconcileSelection()
assert(selection.selectedID == "first")
selection.ingest(event("first","Stop","success"));selection.reconcileSelection()
assert(selection.selectedID == "second")
selection.ingest(event("second","Stop","success"),now:Date().addingTimeInterval(-5));selection.reconcileSelection()
assert(selection.selectedID.isEmpty)
print("auto-select new task, preserve manual selection on tool calls, fallback and empty selection passed")
